[tool.poetry]
name = "pricera.hotline"
version = "0.1.0"
description = ""
authors = []
packages=[
    {include="pricera/hotline/*"}
]

[tool.poetry.dependencies]
python = ">=3.13"
scrapy = "^2.11.0"

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.core.masonry.api"
