name: pre-commit
on: [push]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.13.1'
      - run: pip install pre-commit
      - run: pre-commit run --all-files --show-diff-on-failure
