[tool.poetry]
name = "pricera.models"
version = "0.1.0"
description = ""
authors = []
packages=[
    {include="pricera/models/*"}
]

[tool.poetry.dependencies]

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.core.masonry.api"
